import mutations from "./mutations.js"
import getters from "./getters.js"
import actions from "./actions.js"

export default {
  // namespaced: true,
  state() {
    return {
      bestsellerProducts: [
        {
          id: '7',
          name: 'Hoodie FIRE DRAGON',
          color: 'pomaranczowy',
          price: 249.99,
          image: require("../../../assets/images/7.png"),
          stock: "RESTOCK",
        },
        {
          id: '8',
          name: 'Hoodie UNLUCKY',
          color: 'czarny',
          price: 249.99,
          image: require("../../../assets/images/8.png"),
          stock: "RESTOCK",
        },
        {
          id: '9',
          name: 'Jogger UNSTABLE WORLD slim',
          color: 'czarny',
          price: 249.99,
          image: require("../../../assets/images/9.png"),
          stock: "RESTOCK",
        },
        {
          id: '10',
          name: 'Hoodie Welur 7MORE7',
          color: 'blekit',
          price: 349.99,
          image: require("../../../assets/images/10.png"),
          stock: "RESTOCK",
        },
        {
          id: '11',
          name: 'Jogger Welur 7MORE7',
          color: 'czarny',
          price: 189.99,
          image: require("../../../assets/images/11.png"),
          stock: "RESTOCK",
        },
        {
          id: '12',
          name: 'Hoodie Welur SICARIOS',
          color: 'bordowy',
          price: 349.99,
          image: require("../../../assets/images/12.png"),
          stock: "RESTOCK",
        },
        {
          id: '13',
          name: 'T-SHIRT ALIEN',
          color: 'czarny',
          price: 99.99,
          image: require("../../../assets/images/13.png"),
          stock: "RESTOCK",
        },
        {
          id: '14',
          name: 'Hoodie ALIEN',
          color: 'czarny',
          price: 249.99,
          image: require("../../../assets/images/14.png"),
          stock: "RESTOCK",
        },
      ],

      shopProducts: [
        {
          id: '1',
          name: 'Czapka 77 #1',
          color: 'czarny',
          price: 99.99,
          image: [
            {first: require("../../../assets/images/1.png")},
            {second: require("../../../assets/images/1a.png")},
            {third: require("../../../assets/images/1b.png")},
          ],
          stock: 'RESTOCK',
          category: 'akcesoria',
          info: 'Wykonana z wysokiej jakości wełny Merino 100%',
          gender: 'unisex',
          size: 'uniwersalny',
          qty: 1,
        },
        {
          id: '2',
          name: 'Jogger Welur 7MORE7',
          color: 'blekit',
          price: 189.99,
          image: require("../../../assets/images/2.png"),
          stock: "NOWOSC",
          type: 'spodnie',
        },
        {
          id: '3',
          name: 'Jogger Welur SICARIOS',
          color: 'bialy',
          price: 199.99,
          image: require("../../../assets/images/3.png"),
          stock: "NOWOSC",
          type: 'spodnie',
        },
        {
          id: '4',
          name: 'Hoodie Welur SICARIOS',
          color: 'bezowy',
          price: 349.99,
          image: require("../../../assets/images/4.png"),
          stock: "NOWOSC",
          type: 'hoodie',
        },
        {
          id: '5',
          name: 'Jogger Welur 7MORE7',
          color: 'grafit',
          price: 189.99,
          image: require("../../../assets/images/5.png"),
          stock: "NOWOSC",
          type: 'spodnie',
        },
        {
          id: '6',
          name: 'Hoodie Welur SICARIOS',
          color: 'czarny',
          price: 349.99,
          image: require("../../../assets/images/6.png"),
          stock: "NOWOSC",
          type: 'hoodie',
        },
        {
          id: '7',
          name: 'Hoodie FIRE DRAGON',
          color: 'pomaranczowy',
          price: 249.99,
          image: require("../../../assets/images/7.png"),
          stock: "RESTOCK",
          type: 'hoodie',
        },
        {
          id: '8',
          name: 'Hoodie UNLUCKY',
          color: 'czarny',
          price: 249.99,
          image: require("../../../assets/images/8.png"),
          stock: "RESTOCK",
          type: 'hoodie',
        },
        {
          id: '9',
          name: 'Jogger UNSTABLE WORLD slim',
          color: 'czarny',
          price: 249.99,
          image: require("../../../assets/images/9.png"),
          stock: "RESTOCK",
          type: 'spodnie',
        },
        {
          id: '10',
          name: 'Hoodie Welur 7MORE7',
          color: 'blekit',
          price: 349.99,
          image: require("../../../assets/images/10.png"),
          stock: "RESTOCK",
          type: 'hoodie',
        },
        {
          id: '11',
          name: 'Jogger Welur 7MORE7',
          color: 'czarny',
          price: 189.99,
          image: require("../../../assets/images/11.png"),
          stock: "RESTOCK",
          type: 'spodnie',
        },
        {
          id: '12',
          name: 'Hoodie Welur SICARIOS',
          color: 'bordowy',
          price: 349.99,
          image: require("../../../assets/images/12.png"),
          stock: "RESTOCK",
          type: 'hoodie',
        },
        {
          id: '13',
          name: 'T-SHIRT ALIEN',
          color: 'czarny',
          price: 99.99,
          image: require("../../../assets/images/13.png"),
          stock: "RESTOCK",
          type: 'tshirt',
        },
        {
          id: '14',
          name: 'Hoodie ALIEN',
          color: 'czarny',
          price: 249.99,
          image: require("../../../assets/images/14.png"),
          stock: "RESTOCK",
          type: 'hoodie',
        },
        {
          id: '15',
          name: 'Longsleeve SICARIOS',
          color: 'czarny',
          price: 179.99,
          image: require("../../../assets/images/15.png"),
          stock: "RESTOCK",
          type: 'longsleeve',
        },
      ],

      cart: { items: [], total: 0, qty: 0 }
    }
  },
  mutations: mutations,
  getters: getters,
  actions: actions,
}
